### PR TITLE
Fixes missing lodash require in utils.

### PR DESCRIPTION
**Pull request by Salakar**
image

### CODE REVIEW

**Comment by leeroybrun** [comment]
Great, thanks!

**Comment by Salakar** [comment]
Could you publish a new version to npm? :D Have to use git url at the moment on npm which is a bit annoying, as the npm one crashes because of this issue. 

Thanks!

**Comment by leeroybrun** [comment]
Yes, sure! Sorry for the delay.

I've pushed the new version to npm.

**Comment by Salakar** [comment]
Awesome! Thanks

**Pull request merged**
